<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir;

return array(
    'Craur' => $vendorDir . '/dracoblue/craur/src/Craur.php',
    'CraurCsvReader' => $vendorDir . '/dracoblue/craur/src/CraurCsvReader.php',
    'CraurCsvWriter' => $vendorDir . '/dracoblue/craur/src/CraurCsvWriter.php',
);
