<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir;

return array(
    'Symfony\\Component\\Yaml\\' => array($vendorDir . '/symfony/yaml'),
    'QueryPath' => array($vendorDir . '/querypath/querypath/src'),
    'PHPExcel' => array($vendorDir . '/phpoffice/phpexcel/Classes'),
);
